"""Initial

Revision ID: 2c579ca12444
Revises: 09534746c4c3
Create Date: 2025-11-08 09:24:45.324916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c579ca12444'
down_revision = '09534746c4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments')
    with op.batch_alter_table('historique', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('solde_apres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historique', schema=None) as batch_op:
        batch_op.alter_column('solde_apres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('daily_gain', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('investments_user_email_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investments_pkey'))
    )
    # ### end Alembic commands ###
